/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-28 00:58:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class information_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1683963886000L));
    _jspx_dependants.put("jar:file:/C:/Project/Bookmaroo/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Bookmaroo/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/views/common/../../../WEB-INF/views/common/top3.jsp", Long.valueOf(1687913815298L));
    _jspx_dependants.put("/WEB-INF/views/common/../../../WEB-INF/views/common/bottom.jsp", Long.valueOf(1683960232000L));
    _jspx_dependants.put("/WEB-INF/views/common/../../../WEB-INF/views/common/sideGui.jsp", Long.valueOf(1683608134000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>책마루도서관</title>\r\n");
      out.write("<style>\r\n");
      out.write("	#main{max-width: 1200px; min-height: 682px;}\r\n");
      out.write("	#mid{min-width: 1800px;}\r\n");
      out.write("    #infoTable tr {\r\n");
      out.write(" 		border-bottom: 1px solid black;\r\n");
      out.write("	}\r\n");
      out.write("	#infoTable {\r\n");
      out.write(" 		margin: 0 auto;\r\n");
      out.write(" 		padding: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	#myCarousel {\r\n");
      out.write("  		height: 500px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#libraryPicturer{\r\n");
      out.write("	  	width: 200px;\r\n");
      out.write("	 	height: 100px;\r\n");
      out.write("	}\r\n");
      out.write("	.carousel-item img {\r\n");
      out.write("	  margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	#infoTable th, td {\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- top.jsp -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Inter\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("	html, body{width: 100%; height: 100%; margin: 0; padding: 0;}\r\n");
      out.write("	body {font-family: 'Inter', sans-serif; min-width: 1920px;}\r\n");
      out.write("	header{margin: 0; padding: 0;}\r\n");
      out.write("	#login{display: flex; position: relative; align-items: center; justify-content: space-between; vertical-align: middle; text-align: center;}\r\n");
      out.write("	#login>ul{margin-right: 100px;}\r\n");
      out.write("	#login>ul>li{\r\n");
      out.write("		display: inline-block; \r\n");
      out.write("		font-size: 13px; font-weight: bold; \r\n");
      out.write("		margin-right: 5%; margin-left: 5%; \r\n");
      out.write("		width: 75px;\r\n");
      out.write("	}\r\n");
      out.write("	#login>ul>li>a{text-decoration: none; color: black;}\r\n");
      out.write("	#logo{height: 50px; width: 140px; margin-left: 100px;}\r\n");
      out.write("	#mainCategory a{\r\n");
      out.write("		margin-bottom: 10px; margin-top: 10px; margin-right: 25px; margin-left: 25px;\r\n");
      out.write("		font-size: 17px; font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("		");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("<!-- 			<div id=\"login\" style=\"height: 80px;\"> -->\r\n");
      out.write("\r\n");
      out.write("<!-- 				<ul id=\"login\"> -->\r\n");
      out.write("<!-- 					<li><a href=\"#\">로그인</a></li> -->\r\n");
      out.write("<!-- 					<li style=\"font-size: 15px; color: gray;\">|</li> -->\r\n");
      out.write("<!-- 					<li><a href=\"#\">회원가입</a></li> -->\r\n");
      out.write("<!-- 				</ul> -->\r\n");
      out.write("<!-- 			</div> -->\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"login\" style=\"height: 80px;\">\r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img id=\"logo\" src=\"resources/image/logo.png\"/></a>\r\n");
      out.write("		<ul id=\"login\">\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("	<nav class=\"navbar navbar-expand-sm navbar-light bg-white border-bottom border-top\">\r\n");
      out.write("   <div class=\"collapse navbar-collapse justify-content-center\" id=\"mainCategory\">\r\n");
      out.write("     	<ul class=\"navbar-nav\">\r\n");
      out.write("       	<li class=\"nav-item active\">\r\n");
      out.write("           <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/searchBook.lib\">도서실</a>\r\n");
      out.write("	      </li>\r\n");
      out.write("	      <li class=\"nav-item\">\r\n");
      out.write("	         <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Announcement.bo\">게시판</a>\r\n");
      out.write("	      </li>\r\n");
      out.write("	      <li class=\"nav-item\">\r\n");
      out.write("	         <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Review.bo\">리뷰</a>\r\n");
      out.write("	      </li>\r\n");
      out.write("	      <li class=\"nav-item\">\r\n");
      out.write("	         <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/information.gui\">이용안내</a>\r\n");
      out.write("	      </li>\r\n");
      out.write("	      <li class=\"nav-item\">\r\n");
      out.write("	      		");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	      		");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		    </li>\r\n");
      out.write("     	</ul>\r\n");
      out.write("   	</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" id=\"warning\">\r\n");
      out.write("	<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("   		<div class=\"modal-content rounded-3 shadow\">\r\n");
      out.write("     			<div class=\"modal-body p-4 text-center\">\r\n");
      out.write("					<h1><i class=\"bi bi-exclamation-triangle-fill\" style=\"color: red;\"></i></h1>\r\n");
      out.write("		       		<h3 class=\"mb-0\">로그인이 필요한 서비스입니다</h3>\r\n");
      out.write("     			</div>\r\n");
      out.write("     			<div class=\"modal-footer flex-nowrap p-0\">\r\n");
      out.write("       			<button type=\"button\" class=\"btn btn-lg btn-link fs-6 text-decoration-none col-6 m-0 rounded-0 border-end\" onclick=\"goforLogin()\">\r\n");
      out.write("       				로그인\r\n");
      out.write("       			</button>\r\n");
      out.write("       			<button type=\"button\" class=\"btn btn-lg btn-link fs-6 text-decoration-none col-6 m-0 rounded-0\" data-bs-dismiss=\"modal\">취소</button>\r\n");
      out.write("     			</div>\r\n");
      out.write("   		</div>\r\n");
      out.write(" 	</div>\r\n");
      out.write("	</div>	\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	function needLogin(){\r\n");
      out.write("		$('#warning').modal('show');\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function goforLogin(){\r\n");
      out.write("		location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/loginView.me\";\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	<div class=\"row\" id=\"mid\">\r\n");
      out.write("	  \r\n");
      out.write("	    <!-- 화면 중앙 왼쪽 -->\r\n");
      out.write("	    <div class=\"col-2\">\r\n");
      out.write("	      	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	#subCategory{max-width: 250px;}\r\n");
      out.write("	#subCategory a{\r\n");
      out.write("		padding-bottom: 20px; padding-top: 20px; padding-right: 10px; padding-left: 10px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	.s1{\r\n");
      out.write("		background-color: rgb(67, 115, 230); \r\n");
      out.write("		color: white;\r\n");
      out.write("		border: 1px solid rgb(67, 115, 230);\r\n");
      out.write("		box-shadow: 0 0 0 rgb(67, 115, 230), 0 0 0 1px rgb(67, 115, 230);\r\n");
      out.write("		height:8rem;\r\n");
      out.write("		font-size: 30px;\r\n");
      out.write("		display: flex;\r\n");
      out.write(" 		align-items: center;\r\n");
      out.write("  		justify-content: center;\r\n");
      out.write("	}\r\n");
      out.write("	.s2{\r\n");
      out.write("		background-color: white; \r\n");
      out.write("		color: black;\r\n");
      out.write("		border: 1px solid gray;\r\n");
      out.write("		box-shadow: 0 0 0 #fff, 0 0 0 1px #ddd;\r\n");
      out.write("		height:4rem;\r\n");
      out.write("		font-size: 20px;\r\n");
      out.write("		display: flex;\r\n");
      out.write(" 		align-items: center;\r\n");
      out.write("  		justify-content: center;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"bg-white sidebar fixed-left\" id=\"sideBar\">\r\n");
      out.write("	      <div class=\"sidebar-sticky text-dark\" id=\"subCategory\">\r\n");
      out.write("	        <ul class=\"nav flex-column\">\r\n");
      out.write("	          <li class=\"nav-item\">\r\n");
      out.write("	            <a class=\"nav-link active s1\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/information.gui\">이용안내</a>\r\n");
      out.write("	          </li>\r\n");
      out.write("	          <li class=\"nav-item\">\r\n");
      out.write("	            <a class=\"nav-link s2\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/information.gui\">책마루 안내</a>\r\n");
      out.write("	          </li>\r\n");
      out.write("	          <li class=\"nav-item\">\r\n");
      out.write("	            <a class=\"nav-link s2\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/location.gui\">책마루 위치</a>\r\n");
      out.write("	          </li>\r\n");
      out.write("	          <li class=\"nav-item\">\r\n");
      out.write("	            <a class=\"nav-link s2\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/operationTime.gui\">운영 시간</a>\r\n");
      out.write("	          </li>\r\n");
      out.write("	          <li class=\"nav-item\">\r\n");
      out.write("	            <a class=\"nav-link s2\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/libraryFAQ.gui\">자주 묻는 질문</a>\r\n");
      out.write("	          </li>\r\n");
      out.write("	        </ul>\r\n");
      out.write("	      </div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	    </div>\r\n");
      out.write("		    \r\n");
      out.write("	    <!-- 중앙 영역 -->\r\n");
      out.write("	    <div class=\"col-8\" id=\"main\">\r\n");
      out.write("		    <br>\r\n");
      out.write("	        <div class=\"d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom\">\r\n");
      out.write("				<h1 class=\"h1\">책마루 안내</h1>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      	<br>\r\n");
      out.write("			<div>\r\n");
      out.write("			    <table class=\"text-center table-bordered table-striped\" id=\"infoTable\">\r\n");
      out.write("			      <thead>\r\n");
      out.write("			      	<tr>\r\n");
      out.write("			      		<th class=\"bg-light\">층별</th>\r\n");
      out.write("			      		<th class=\"bg-light\">시설</th>\r\n");
      out.write("			      		<th class=\"bg-light\">이용대상및 자료</th>\r\n");
      out.write("			      		<th class=\"bg-light\">전화번호</th>\r\n");
      out.write("			      		<th class=\"bg-light\">비고</th>\r\n");
      out.write("			      	</tr>\r\n");
      out.write("			      </thead>\r\n");
      out.write("			      <tbody>\r\n");
      out.write("			        <tr>\r\n");
      out.write("			          <td>1층</td>\r\n");
      out.write("			          <td>어린이자료실<br>안내데스크</td>\r\n");
      out.write("			          <td>어린이열람실, 체험코너, 시설 이용 문의</td>\r\n");
      out.write("			          <td>123-4567</td>\r\n");
      out.write("			          <td>장애인화장실</td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			        <tr>\r\n");
      out.write("			          <td>2층</td>\r\n");
      out.write("			          <td>일반자료실</td>\r\n");
      out.write("			          <td>일반도서 열람 및 대출, 회원증발급, 신문, 잡지, 참고도서</td>\r\n");
      out.write("			          <td>123-4567</td>\r\n");
      out.write("			          <td></td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			        <tr>\r\n");
      out.write("			          <td>3층</td>\r\n");
      out.write("			          <td>디지철자료실</td>\r\n");
      out.write("			          <td>DVD, 인터넷, 개인 노트북사용, 복사, 출력 및 스캐너 사용</td>\r\n");
      out.write("			          <td>123-4567</td>\r\n");
      out.write("			          <td>좌석수 22</td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			        <tr>\r\n");
      out.write("			          <td>4층</td>\r\n");
      out.write("			          <td>열람실<br>휴게실</td>\r\n");
      out.write("			          <td>일반열람실, 음료수, 커피 자동판매기 이용</td>\r\n");
      out.write("			          <td>123-4567</td>\r\n");
      out.write("			          <td>좌석수 54</td>\r\n");
      out.write("			        </tr>\r\n");
      out.write("			      </tbody>\r\n");
      out.write("			    </table>\r\n");
      out.write("			  </div>\r\n");
      out.write("			  <br>\r\n");
      out.write("		  	  <div id=\"libraryPicture\" class=\"carousel carousel-dark slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("				  <div class=\"carousel-indicators\">\r\n");
      out.write("				    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("				    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("				    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("				    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"3\" aria-label=\"Slide 4\"></button>\r\n");
      out.write("				    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"4\" aria-label=\"Slide 5\"></button>\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <div class=\"carousel-inner\">\r\n");
      out.write("				    <div class=\"carousel-item active\">\r\n");
      out.write("				      <img src=\"resources/image/libraryImage01.jpg\" class=\"d-block\" alt=\"libraryImage\">\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <div class=\"carousel-item\">\r\n");
      out.write("				      <img src=\"resources/image/libraryImage02.jpg\" class=\"d-block\" alt=\"libraryImage\">\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <div class=\"carousel-item\">\r\n");
      out.write("				      <img src=\"resources/image/libraryImage03.jpg\" class=\"d-block\" alt=\"libraryImage\">\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <div class=\"carousel-item\">\r\n");
      out.write("				      <img src=\"resources/image/libraryImage04.jpg\" class=\"d-block\" alt=\"libraryImage\">\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <div class=\"carousel-item\">\r\n");
      out.write("				      <img src=\"resources/image/libraryImage05.jpg\" class=\"d-block\" alt=\"libraryImage\">\r\n");
      out.write("				    </div>\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#libraryPicture\" data-bs-slide=\"prev\">\r\n");
      out.write("				    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("				    <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("				  </button>\r\n");
      out.write("				  <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#libraryPicture\" data-bs-slide=\"next\">\r\n");
      out.write("				    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("				    <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("				  </button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("		</div>\r\n");
      out.write("	    \r\n");
      out.write("	    <!-- 화면 중앙 오른쪽 여백 생성 -->\r\n");
      out.write("	    <div class=\"col-2\">\r\n");
      out.write("	    </div>\r\n");
      out.write("	    \r\n");
      out.write("  	</div>\r\n");
      out.write("	  \r\n");
      out.write("	<!-- bottom.jsp -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	#ftnav{text-align: left; margin-left: 30px; font-size: 13px; }\r\n");
      out.write("	#ftnav a{text-decoration: none; color: white;}\r\n");
      out.write("	#ftp{text-align: left; margin-left: 10px; font-size: 13px; line-height:170%;}\r\n");
      out.write("	#anker{margin-left: 50px; vertical-align: middle; text-align: right; margin-right: 30px; position: fixed; right:15px;  bottom: 35px; }\r\n");
      out.write("	.bi-arrow-up-circle-fill{color:black; font-size: 40px;}\r\n");
      out.write("	footer {\r\n");
      out.write("		display:flex;  \r\n");
      out.write("		align-items:center; \r\n");
      out.write("		position: relative;\r\n");
      out.write("		bottom: 0;\r\n");
      out.write("		height: 180px; width: 100%;\r\n");
      out.write("		min-width: 1000px;\r\n");
      out.write("		background: rgb(67, 115, 230); \r\n");
      out.write("		color: white; \r\n");
      out.write("		align-items: center; justify-content: space-between; \r\n");
      out.write("		vertical-align: middle; text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div id=\"a1\">\r\n");
      out.write("			<nav id=\"ftnav\">\r\n");
      out.write("		   		<b>\r\n");
      out.write("		   			<a target='_blank'>&nbsp;&nbsp;이용약관&nbsp;&nbsp;&nbsp;&nbsp;</a> |&nbsp;&nbsp;&nbsp;\r\n");
      out.write("		    		<a target='_blank'>&nbsp;개인정보취급방침&nbsp;&nbsp;&nbsp;&nbsp;</a> |&nbsp;&nbsp;&nbsp;\r\n");
      out.write("		    		<a target='_blank'>&nbsp;문의</a>\r\n");
      out.write("		    	</b>\r\n");
      out.write("		    	<br/>\r\n");
      out.write("		    	<br/>\r\n");
      out.write("			    <p id=\"ftp\">\r\n");
      out.write("			    	<span id=\"sp2\">책마루도서관 ｜ 사업자등록번호 : 123-45-67890 ｜ 서울 종로 제2023-01호 ｜ 대표자 : 박지은 ｜ 책임자 : 우진기</span><br/>\r\n");
      out.write("			    	<span>서울특별시 중구 남대문로 120 그레이츠 청계(구 대일빌딩) 2F, 3F</span><br/>\r\n");
      out.write("			    	<span id=\"sp1\">Copyright © 2023 Book Maru Library All Right Reserved</span>\r\n");
      out.write("			    </p>\r\n");
      out.write("		    </nav>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"anker\"><a href=\"#\" onclick=\"scrollToElement('anchorPoint')\" ><i class=\"bi bi-arrow-up-circle-fill\"></a></i></div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<script>\r\n");
      out.write("	function scrollToElement(id) {\r\n");
      out.write("		  const element = document.getElementById(id);\r\n");
      out.write("		  element.scrollIntoView({ behavior: 'auto' });\r\n");
      out.write("		}\r\n");
      out.write("	</script>		\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/common/../../../WEB-INF/views/common/top3.jsp(35,2) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/../../../WEB-INF/views/common/top3.jsp(35,2) '${ pageContext.servletContext.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.servletContext.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/common/../../../WEB-INF/views/common/top3.jsp(35,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/common/../../../WEB-INF/views/common/top3.jsp(35,2) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("application");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/common/../../../WEB-INF/views/common/top3.jsp(52,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/loginView.me\">로그인</a></li>\r\n");
          out.write("				<li style=\"font-size: 15px; color: gray;\">|</li>\r\n");
          out.write("				<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/signUp.me\">회원가입</a></li>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/common/../../../WEB-INF/views/common/top3.jsp(57,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/common/../../../WEB-INF/views/common/top3.jsp(58,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty loginUser.kakaoId }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logout.me\" style=\"text-decoration: none; color:black; font-size: 13px; font-weight: bold;\">로그아웃</a>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/common/../../../WEB-INF/views/common/top3.jsp(61,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty loginUser.kakaoId }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<a href=\"https://kauth.kakao.com/oauth/logout?client_id=3820ee86989bf11805e157a18f4e15b1&logout_redirect_uri=http://112.221.156.35:8080/bookmaroo/logout.me\" style=\"text-decoration: none; color:black; font-size: 13px; font-weight: bold;\">로그아웃</a>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/common/../../../WEB-INF/views/common/top3.jsp(87,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		         	<a class=\"nav-link\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/myInfoForm.me\">마이페이지</a>\r\n");
          out.write("	      		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/views/common/../../../WEB-INF/views/common/top3.jsp(90,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		         	<a class=\"nav-link\" onclick=\"needLogin()\" style=\"cursor: pointer;\">마이페이지</a>\r\n");
          out.write("	      		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }
}
